services:
  # --- CONTENEUR 1 : LA BASE DE DONNÉES ---
  mongodb:
    image: mongo:latest
    container_name: mongodb_server
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - mongo_data:/data/db # Persistance des données MongoDB

  # --- CONTENEUR 2 : LE SCRIPT PYTHON DE MIGRATION ---
  migration_app:
    build: .
    container_name: python_migration
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://admin:admin@mongodb:27017/?authSource=admin
      - CSV_PATH=/app/src/data/healthcare_dataset.csv
    volumes:
      - ./src/data:/app/src/data # Volume pour isoler et persister/externaliser le CSV (recommandation projet)[cite: 8]

volumes:
  mongo_data: