services:
  # --- CONTENEUR 1 : LA BASE DE DONNÉES ---
  mongodb:
    image: mongo:latest
    container_name: mongodb_server
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - mongo_data:/data/db # Persistance des données exigée par le projet

  # --- CONTENEUR 2 : TON SCRIPT PYTHON ---
  migration_app:
    build: . # Dit à Docker de lire le Dockerfile qu'on vient de créer
    container_name: python_migration
    depends_on:
      - mongodb # Essentiel : Python doit attendre que MongoDB démarre
    environment:
      # L'URI pour que Python trouve la base de données sur le réseau virtuel de Docker
      - MONGO_URI=mongodb://admin:admin@mongodb:27017/?authSource=admin

volumes:
  mongo_data: